version: '3'

services:
  webserver:
    image: quay.io/gwesfisher/dfsite:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - /dfsite/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /dfsite/certbot/conf:/etc/letsencrypt/:ro
